site_name: GCP Docs
theme:
  name: material
  font:
    text: Be Vietnam Pro
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Dark mode
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Light mode
      accent: deep purple
  features:
    - navigation.footer
    - navigation.top
    - toc.follow
  icon:
    repo: fontawesome/brands/github
copyright: Copyright &copy; 2025 Rohit
extra:
  generator: false
repo_url: https://github.com/rohitsinghpanwar/mkdocs
repo_name: GCP Documentation
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables  



